export const GET_EMP_DATA = "GET_EMP_DATA", 
SET_EMP_DATA = "EMP_DATA", 
INITIAL_GET_DATA = "INITIAL_GET_DATA",
DELETE_EMP_DATA = "DELETE_EMP_DATA",
EDIT_ROW = "EDIT_ROW",
SET_EMP_NEWDATA = "SET_EMP_NEWDATA"